### ISSUE TITLE
环境：win10，JKD8，neo4j-community-3.5.35。导入neo4j.dump成功，启动失败

### ISSUE THREAD

**Issue by jeffnudt** [huyuanxin/CMeKGCrawler#2]
D:\neo4j-community-3.5.35\bin>neo4j-admin load --from=D:/neo4j.dump --database=graph.db  --force
Done: 148 files, 551.6MiB processed.

D:\neo4j-community-3.5.35\bin>neo4j.bat  console
2022-11-04 02:59:07.152+0000 INFO  ======== Neo4j 3.5.35 ========
2022-11-04 02:59:07.162+0000 INFO  Starting...
2022-11-04 02:59:08.955+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50ecde95' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=2, byteOffset=16} and entry version null". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50ecde95' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=2, byteOffset=16} and entry version null".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50ecde95' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=2, byteOffset=16} and entry version null".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@50ecde95' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=2, byteOffset=16} and entry version null".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, D:\neo4j-community-3.5.35\data\databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:148)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@6ff65192' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=2, byteOffset=16} and entry version null".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
        ... 9 more
Caused by: java.lang.RuntimeException: Error reading transaction logs, recovery not possible. To force the database to start anyway, you can specify 'unsupported.dbms.tx_log.fail_on_corrupted_log_files=false'. This will try to recover as much as possible and then truncate the corrupt part of the transaction log. Doing this means your database integrity might be compromised, please consider restoring from a consistent backup instead.
        at org.neo4j.kernel.recovery.Recovery.throwUnableToCleanRecover(Recovery.java:160)
        at org.neo4j.kernel.recovery.LogTailScanner.findLogTail(LogTailScanner.java:147)
        at org.neo4j.kernel.recovery.LogTailScanner.getTailInformation(LogTailScanner.java:260)
        at org.neo4j.kernel.impl.transaction.log.LogVersionUpgradeChecker.check(LogVersionUpgradeChecker.java:48)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:349)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 14 more
Caused by: org.neo4j.kernel.impl.transaction.log.entry.UnsupportedLogVersionException: Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=2, byteOffset=16} and entry version null
        at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.byVersion(LogEntryVersion.java:169)
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:80)
        at org.neo4j.kernel.impl.transaction.log.LogEntryCursor.next(LogEntryCursor.java:54)
        at org.neo4j.kernel.recovery.LogTailScanner.findLogTail(LogTailScanner.java:99)
        ... 18 more
2022-11-04 02:59:08.960+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by huyuanxin** [comment]
[可以试试看这个方法](https://blog.csdn.net/weixin_41091001/article/details/123269176)

**Comment by jeffnudt** [comment]
> [可以试试看这个方法](https://blog.csdn.net/weixin_41091001/article/details/123269176)

照着操作一遍还是不行，浏览器访问localhost:7474报无法访问此网站，netstat 查不到7474端口

D:\neo4j-community-3.5.35\bin>neo4j install-service

D:\neo4j-community-3.5.35\bin>neo4j start
Neo4j service started

D:\neo4j-community-3.5.35\bin>neo4j install-service

D:\neo4j-community-3.5.35\bin>neo4j start
Neo4j service started

D:\neo4j-community-3.5.35\bin>netstat -nao

活动连接

  协议  本地地址          外部地址        状态           PID
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       64832
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       1204
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:1688           0.0.0.0:0              LISTENING       5408
  TCP    0.0.0.0:3308           0.0.0.0:0              LISTENING       64028
  TCP    0.0.0.0:4433           0.0.0.0:0              LISTENING       64832
  TCP    0.0.0.0:5040           0.0.0.0:0              LISTENING       8600
  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       62012
  TCP    0.0.0.0:10014          0.0.0.0:0              LISTENING       66244
  TCP    0.0.0.0:13137          0.0.0.0:0              LISTENING       66800

**Comment by jeffnudt** [comment]
能把整个带图谱数据的neo4j-community打个包发到我邮箱吗？15810102878@163.com  谢谢哥们

**Comment by huyuanxin** [comment]
我现在也没有这个库了
